### ISSUE TITLE
Method Awcodes\Overlook\Overlook::getRoutes does not exist.

### ISSUE THREAD

**Issue by JoseJunior-L4** [awcodes/overlook#2]
Method Awcodes\Overlook\Overlook::getRoutes does not exist.
at projectDir\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:87

     83▕      */
     84▕     public static function __callStatic($method, $parameters)
     85▕     {
     86▕         if (! static::hasMacro($method)) {
  ➜  87▕             throw new BadMethodCallException(sprintf(
     88▕                 'Method %s::%s does not exist.', static::class, $method
     89▕             ));
     90▕         }
     91▕

  i   Bad Method Call: Did you mean Awcodes\Overlook\Overlook::getRules() ?

**Comment by awcodes** [comment]
Sorry, I need more information than this in order to replicate what you are seeing. Overlook doesn't use getRoutes directly, so I'm not sure why you are seeing that.

**Comment by babatundeakinse** [comment]
@JoseJunior-L4 this issue is happening because you've added the ```Awcodes\Overlook\Overlook``` in config to the wrong section, remove it from the pages, the correct section is the widgets section in config.

Thanks
