### ISSUE TITLE
Style Bug

### ISSUE THREAD

**Issue by EG-Mohamed** [awcodes/overlook#23]
### Filament Version

v3

### Plugin Version

v2.0.0

### PHP Version

8.1.7

### Problem description

![image](https://github.com/awcodes/overlook/assets/23424932/65a9194f-ffa7-4c11-a2e4-2da6e82230a5)

Boxes has style problemhave

### Expected behavior

The box fit the content

### Steps to reproduce

Just add `OverlookPlugin::make(),` and `OverlookWidget::class,` and the problem will appear

**Comment by awcodes** [comment]
Please read the README. It's the first thing mentioned after composer install in the Installation steps. :)

**Comment by EG-Mohamed** [comment]
@awcodes Sorry my bad !
