### ISSUE TITLE
css not included on fresh install for Filament3

### ISSUE THREAD

**Issue by SchizoDuckie** [awcodes/overlook#26]
### Filament Version

v3

### Plugin Version

2.x

### PHP Version

php 8.1

### Problem description

I experienced the same problem as #23

The problem seems to stem from the css definitions not being available in the v2.x branch.

The widget refers to these classes:

https://github.com/awcodes/overlook/blob/49fe6171b92596630b392da8e24d30ad96e414cc/resources/views/widget.blade.php#L26

But their definitions are, as far as i can see, only defined in the 1.x branch:

https://github.com/awcodes/overlook/blob/1.x/resources/dist/overlook.css

I manually injected the contents of this file in my theme.css and removed some stuff to make it look okay with my dark mode,
and now it looks beautiful.

![image](https://github.com/awcodes/overlook/assets/111710/29c8fde8-f005-4910-8b23-6ce422dee9c6)

As i'm quite new to filament I don't have a clue how to make the proper PR for this yet, but I hope this helps someone else.

### Expected behavior

Icons should be properly styled.

### Steps to reproduce

- install and configure plugin on fresh filament 3.x install (including enabling theme)
- observe icons being unstyled

**Comment by awcodes** [comment]
If you follow the readme and set everything up correctly in your custom theme it works correctly.
