### ISSUE TITLE
Wrong height widget

### ISSUE THREAD

**Issue by DeviJv** [awcodes/overlook#27]
### Filament Version

v3

### Plugin Version

2

### PHP Version

8.2

### Problem description

why my widget look like this :(

<img width="689" alt="image" src="https://github.com/awcodes/overlook/assets/26791396/821d5b36-8749-44bb-8171-df72704cab30">

### Expected behavior

how to setting height?

### Steps to reproduce

how to setting height?

### Relevant log output

```shell
how to setting height?
```

**Comment by eelco2k** [comment]
i've got the same issue, what was the solution?

**Comment by awcodes** [comment]
You didn't follow the readme install instructions about setting up a theme for filament.

**Comment by eelco2k** [comment]
found the issue, in the custom theme filament there was a paragraph which i did not see that good because of an horizontal scoll. (was hidden)

i had to register the theme in my panelProvider like so:

->viteTheme('resources/css/filament/admin/theme.css')

**Comment by DeviJv** [comment]
i solved 
just add custom theme bro

**Comment by kingmaker-agm** [comment]
@eelco2k @DeviJv 

What should I have to do if I'm not using a **Custom Theme** for _Filament v3_? Is it absolutely necessary to have a _custom theme setup_ for this to work?

@awcodes you can also comment on this.
https://github.com/awcodes/overlook/issues/41

**Comment by kingmaker-agm** [comment]
For People who doesn't know how to Setup the **Custom Theme** in **Filament `v3`**, kindly follow the Instruction in [this comment](https://github.com/awcodes/overlook/issues/41#issuecomment-2155832841) or below link.

https://github.com/awcodes/overlook/issues/41#issuecomment-2155832841
