### ISSUE TITLE
overlook ist not registered for panel

### ISSUE THREAD

**Issue by grafst** [awcodes/overlook#36]
### Filament Version

v3

### Plugin Version

v2.2

### PHP Version

v8.3.3

### Problem description

I get the error 
_Plugin [awcodes/overlook] is not registered for panel [admin]._
when opening the dashboard.

### Expected behavior

See a nice OVerview of my resources :)

### Steps to reproduce

In the AdminPanelProvider register the widget like the following

``` 
->widgets([
  . . .
  OverlookWidget::class,
])
```

**Comment by awcodes** [comment]
Did you not add the plugin to the plugins() array in the panel provider?

See the 'usage' section of the Readme.
