### ISSUE TITLE
Unable to Publish Config

### ISSUE THREAD

**Issue by NinjaLabs-Dev** [awcodes/overlook#4]
**Issue**: Error produced while trying to publish the config
**Reproduction**: 
1. Run `php artisan vendor:publish --tag="overlook-config"`
2. Issue presented

**Evidence of Issue**:
![Evidence](https://cdn.ninjalabs.dev/zGMkt)

**Comment by awcodes** [comment]
if you run just `php vendor:publish` do you see overlook in the list?

**Comment by NinjaLabs-Dev** [comment]
Thanks for the response.

I don't sadly, I do have the service provider though.

![Configs](https://cdn.ninjalabs.dev/E5MoM)

![Providers](https://cdn.ninjalabs.dev/XbNof)

**Comment by awcodes** [comment]
odd. maybe try a `php artisan optimize:clear` or a `composer dump-autoload`?

I just used it yesterday with no problems.

**Comment by NinjaLabs-Dev** [comment]
Sadly no luck,

I do however now have the overlook translations and views which I didn't have before. A very strange one I have to say

![Image](https://cdn.ninjalabs.dev/Y4RjJ)

**Comment by awcodes** [comment]
You could always copy it out of the vendor directory manually. Make sure you're on the latest version too. The config was added in v1.0.2

**Comment by NinjaLabs-Dev** [comment]
Ah, that would be it. For some reason, Composer installed 1.0 instead of 1.0.2. 

Removed and readded and all working now. Thanks for the help 😅
