### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by abbasmashaddy72** [awcodes/overlook#40]
### Filament Version

v3

### Plugin Version

v2.2

### PHP Version

PHP 8.3

### Problem description

Class "NumberFormatter" not found

A class import is missing
You have a missing class import. Try importing this class: PhpOffice\PhpSpreadsheet\Style\NumberFormat\NumberFormatter.

### Expected behavior

To Work Normally If I disable abbreviateCount it works

### Steps to reproduce

1. Normally Update the Code
2. Opened Dashboard Found that I got this error

### Relevant log output

```shell
Error Share Link

https://flareapp.io/share/V7jdNAjm
```

**Comment by awcodes** [comment]
Sounds like your server is missing the 'ext-intl' extension.

**Comment by abbasmashaddy72** [comment]
Let me check

**Comment by abbasmashaddy72** [comment]
The extension was available maybe there was some issues within my project files or composer package as was migrating from 10 to 11 now it is fixed.

But anyway Thanks
